---

stages:
  - build

install:
  - python3 -m pip install cibuildwheel

script:
  - python3 -m cibuildwheel --output-dir wheelhouse
  - python3 -m pip install twine

jobs:
  include:

  ##############################################################################
  # LINUX BUILDS
  ##############################################################################

    - name: Build wheels on Linux and deploy
      stage: build
      os: linux
      dist: bionic
      services: docker
      language: python
      python: 3.8
      after_success:
        - ./scripts/pypi-upload.sh sdist

  ##############################################################################
  # MACOS BUILDS
  ##############################################################################

    - name: Build wheels on Mac and deploy
      stage: build
      os: osx
      osx_image: xcode11
      language: shell
      after_success:
        - ./scripts/pypi-upload.sh

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_BEFORE_ALL_MACOS=./scripts/prepare-cibw-macos.sh
    - CIBW_BEFORE_ALL_LINUX=./scripts/prepare-cibw-linux.sh
    - CIBW_BUILD="*x86_64"
    - CIBW_SKIP="pp*"
    - PYPI_TEST=true

branches:
  only:
    - main
